### ISSUE TITLE
how to install package ?

### ISSUE THREAD

**Issue by mohamedyasser** [laravel-admin-extensions/translation#3]
[InvalidArgumentException]
  Could not find package laravel-admin-ext/translation at any version for your minimum-stability (stable). Check the
  package spelling or your minimum-stability

**Comment by kevdespres** [comment]
In your composer.json add this : 
`"repositories": [
        {
            "type": "git",
            "url": "https://github.com/laravel-admin-extensions/translation"
        }
    ]`
and this
`"require": {
      "laravel-admin-ext/translation" : "dev-master"
}`

After that, I can access to the repo but it still does not work. And I don't know how to configure it.

**Comment by mohamedyasser** [comment]
I'm make it like that from being but the plugin still under developing

**Comment by alihastam** [comment]
I think this work with trans() function. for example:
`$content->description(trans('admin::lang.create'));`

**Comment by doominating** [comment]
I've commented about [here](https://github.com/laravel-admin-extensions/translation/issues/5#issuecomment-388256206)

**Comment by mohamedyasser** [comment]
thank you ,doominationg
