### ISSUE TITLE
为啥没有安装文档呢？

### ISSUE THREAD

**Issue by sampanhuang** [laravel-admin-extensions/translation#5]
为啥没有安装文档呢？
这样的安装步骤行不行呢？

$ composer require laravel-admin-extensions/translation -vvv
$ php artisan migrate --path=vendor/laravel-admin-ext/translation /database/migrations
$ php artisan admin:import translation 

提示找不到这个包

Could not find package laravel-admin-extensions/translation at any version
for your minimum-stability (stable). Check the package spelling or your min
imum-stability

**Comment by doominating** [comment]
This is because this package isn't available at https://packagist.org
@z-song needs to upload the package to there, them the 'composer require' command will works as expected, like in the others packages eg: 'import' etc.

**Comment by sampanhuang** [comment]
thank you ,doominationg
